name: Python Pipenv Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]  # Add other Python versions if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pipenv
      run: |
        # pip install pipenv
        pip install git+https://github.com/pypa/pipenv.git@transitive-sys-markers

    - name: Install dependencies
      run: |
        pipenv install --dev
        pipenv run pip freeze

    - name: Run test.py script
      run: |
        pipenv run python test.py
